### ISSUE TITLE
Write down a clear definition of what's considered as selfbotting

### ISSUE THREAD

**Issue by cyyynthia** [powercord-community/guidelines#3]
As discussed in [NickProtect plugin suggestion](https://github.com/powercord-community/suggestions/issues/68), what is considered as selfbotting is subjective and the opinions can vary from one person to another. Since we're in an environment where Discord doesn't have any guidelines since what we are doing is, no matter what we do, against the ToS, there is as of now no clear definition of what's "selfbotting".

Since we've decided to write guidelines to define "what breaks ToS to a "safe" degree", adding a clear definition of selfbotting seems like a good idea.

As of now, the definition I have in mind is "Any action (sending a message, reacting, changing nickname, ...) that is not triggered by an interaction from the user". Feel free to suggest improvements or other definitions if you have another in mind

**Comment by LandenStephenss** [comment]
I agree with what you said, basically anything automated would be self botting or even a command to change something related to your discord account

**Comment by alikindsys** [comment]
My two cents : If it involves any PUT/POST requests to the discord api it can be considered selfbotting.

**Comment by cyyynthia** [comment]
Well, GET requests can fall into the selfbotting category as well if used for scraping purposes, as much as POST/PATCH/DELETE requests. I don't think we should treat methods differently

**Comment by alikindsys** [comment]
Indeed, The original idea was "If it involves any requests" but I was trying to not be that harsh. 
Final edit: "Any requests to the api that aren't originated from an user action" seems to be a good definition.

**Comment by cyyynthia** [comment]
Updating the issue as some new discussion regarding this topic happened in Powercord's support channels

```
botherjacob - Yesterday at 17:57
is a plugin that deletes all own messages from a channel (with a delay, so it's not spamming the api) considered okay according to the guidelines?

Bowser65 - Yesterday at 18:02
In my opinion it'd fall under selfbotting category

botherjacob - Yesterday at 18:20
well you could also say that any plugin that has commands like urban e.g.

Olykir - Yesterday at 18:30
commands don’t spam the api tho

Bowser65 - Yesterday at 18:32
Well the problem is that we don't have a clear definition of what's considered as selfbotting
A command like urban sends a single message that you could've copy/pasted from somewhere else, it's something you can technically do without a plugin
deleting all of your messages required indexing which is a questionable practice and triggers a lot of API calls
That's the reasonning on why commands like urban (or even the built-in tag plugin) are allowed under the plugin guidelines

botherjacob - Yesterday at 18:39
well when you add a reasonable delay, you could also delete all your messages manually, it's just annoying
i'm talking about a few seconds delay for each deletion

Kyza - Yesterday at 18:52
Selfbotting is the automation of multiple tasks with little to no user input. Even if you add a delay it fits the description.

botherjacob - Yesterday at 19:30
yeah i get that point
```
